apiVersion: apps/v1
kind: Deployment
metadata:
  name: otter-gateway
  labels:
    app: otter-gateway
spec:
  replicas: 4
  selector:
    matchLabels:
      app: otter-gateway
  template:
    metadata:
      labels:
        app: otter-gateway
    spec:
      containers:
        - name: otter-gateway
          image: quay.io/otter-im/gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: SERVICE_ENV
              value: prod
            - name: IDENTITY_HOST
              value: $(OTTER_IDENTITY_SERVICE_HOST)
            - name: IDENTITY_PORT
              value: $(OTTER_IDENTITY_SERVICE_PORT)
            - name: POSTGRES_ADDRESS
              value: $(OTTER_PGDB_SERVICE_HOST):$(OTTER_PGDB_SERVICE_PORT) # Assume using postgres-operator
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auth.otter-pgdb.credentials.postgresql.acid.zalan.do
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth.otter-pgdb.credentials.postgresql.acid.zalan.do
                  key: password
            - name: REDIS_NODES
              value: $(REDIS_SENTINEL_SERVICE_HOST):$(REDIS_SENTINEL_SERVICE_PORT)
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-sentinel
                  key: redis-password
