apiVersion: v1
kind: Service
metadata:
  name: otter-gateway
spec:
  type: LoadBalancer
  selector:
    app: otter-gateway
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
